---
# Source: speedcube-events/templates/cron_job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: speedcube-events-cron
  labels:
    helm.sh/chart: speedcube-events-0.1.0
    app.kubernetes.io/name: speedcube-events
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: speedcube-events
              image: "c4stus/speedcube-events:sha-38ae6b5"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - ./speedcube-events && ./speedcube-events exportDatabase
              env:
                - name: HOME_LAT
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: HOME_LAT
                - name: HOME_LON
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: HOME_LON
                - name: MAPS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: MAPS_TOKEN
                - name: MAIL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: MAIL_TOKEN
                - name: AWS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: AWS_API_KEY
                - name: AWS_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: AWS_API_SECRET
                - name: MAIL_FROM_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: MAIL_FROM_NAME
                - name: MAIL_FROM_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: MAIL_FROM_EMAIL
                - name: NOTIFY_EMAILS
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: NOTIFY_EMAILS
                - name: TABLE_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: TABLE_NAME
                - name: AWS_S3_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: AWS_S3_API_KEY
                - name: AWS_S3_API_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: AWS_S3_API_SECRET
                - name: S3_BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: S3_BUCKET_NAME
          restartPolicy: OnFailure
