apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "speedcube-events.fullname" . }}-cron
  labels:
    {{- include "speedcube-events.labels" . | nindent 4 }}
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - ./speedcube-events
              env:
                {{- range .Values.envs }}
                - name: {{ . }}
                  valueFrom:
                    secretKeyRef:
                      name: "speedcube-events-secrets"
                      key: {{ . }}
                {{- end }}
          restartPolicy: OnFailure
